INSERT INTO label(label_id, name)
VALUES (1, 'Sony'),
       (2, 'Rhino'),
       (3, 'Columbia'),
       (4, 'Intes'),
       (5, 'Impulse Records'),
       (6, 'EMI UK'),
       (7, 'Warner Bros'),
       (8, 'XL Recordings'),
       (9, 'A&M'),
       (10, 'Grp Records'),
       (11, 'Parlophone'),
       (12, 'EMI'),
       (13, 'Wea'),
       (14, 'STOTH'),
       (15, 'Domino'),
       (16, 'Capitol'),
       (17, 'Discipline Us'),
       (18, 'Aftermath'),
       (19, 'Legacy');
